// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonumentosOnline.Data;

namespace MonumentosOnline.Migrations
{
    [DbContext(typeof(Monumentos_OnlineDB))]
    [Migration("20210425183511_DadosTabelas")]
    partial class DadosTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MonumentosOnline.Models.CaractMonumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CaracteristicaFK")
                        .HasColumnType("int");

                    b.Property<int>("MonumentoFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaracteristicaFK");

                    b.HasIndex("MonumentoFK");

                    b.ToTable("CaractMonumentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaracteristicaFK = 1,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 2,
                            CaracteristicaFK = 2,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 3,
                            CaracteristicaFK = 3,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 4,
                            CaracteristicaFK = 4,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 5,
                            CaracteristicaFK = 5,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 6,
                            CaracteristicaFK = 6,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 7,
                            CaracteristicaFK = 7,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 8,
                            CaracteristicaFK = 8,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 9,
                            CaracteristicaFK = 9,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 10,
                            CaracteristicaFK = 10,
                            MonumentoFK = 1
                        },
                        new
                        {
                            Id = 11,
                            CaracteristicaFK = 2,
                            MonumentoFK = 2
                        },
                        new
                        {
                            Id = 12,
                            CaracteristicaFK = 4,
                            MonumentoFK = 2
                        },
                        new
                        {
                            Id = 13,
                            CaracteristicaFK = 3,
                            MonumentoFK = 3
                        },
                        new
                        {
                            Id = 14,
                            CaracteristicaFK = 4,
                            MonumentoFK = 3
                        },
                        new
                        {
                            Id = 15,
                            CaracteristicaFK = 1,
                            MonumentoFK = 4
                        },
                        new
                        {
                            Id = 16,
                            CaracteristicaFK = 2,
                            MonumentoFK = 4
                        },
                        new
                        {
                            Id = 17,
                            CaracteristicaFK = 3,
                            MonumentoFK = 4
                        },
                        new
                        {
                            Id = 18,
                            CaracteristicaFK = 4,
                            MonumentoFK = 4
                        },
                        new
                        {
                            Id = 19,
                            CaracteristicaFK = 2,
                            MonumentoFK = 5
                        },
                        new
                        {
                            Id = 20,
                            CaracteristicaFK = 10,
                            MonumentoFK = 5
                        },
                        new
                        {
                            Id = 21,
                            CaracteristicaFK = 1,
                            MonumentoFK = 6
                        },
                        new
                        {
                            Id = 22,
                            CaracteristicaFK = 2,
                            MonumentoFK = 6
                        },
                        new
                        {
                            Id = 23,
                            CaracteristicaFK = 3,
                            MonumentoFK = 6
                        },
                        new
                        {
                            Id = 24,
                            CaracteristicaFK = 4,
                            MonumentoFK = 6
                        },
                        new
                        {
                            Id = 25,
                            CaracteristicaFK = 7,
                            MonumentoFK = 6
                        },
                        new
                        {
                            Id = 26,
                            CaracteristicaFK = 8,
                            MonumentoFK = 6
                        },
                        new
                        {
                            Id = 27,
                            CaracteristicaFK = 12,
                            MonumentoFK = 7
                        },
                        new
                        {
                            Id = 28,
                            CaracteristicaFK = 14,
                            MonumentoFK = 8
                        });
                });

            modelBuilder.Entity("MonumentosOnline.Models.Caracteristicas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClassPatrimonial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estilo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caracteristicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Gótico",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 2,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Gótico",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 3,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Manuelino",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 4,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Manuelino",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 5,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Renascentista",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 6,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Renascentista",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 7,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Maneirismo",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 8,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Maneirismo",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 9,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Românico",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 10,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Românico",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 11,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Medieval",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 12,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Medieval",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 13,
                            ClassPatrimonial = "Património Mundial",
                            Estilo = "Barroco",
                            Tipo = "Edifício"
                        },
                        new
                        {
                            Id = 14,
                            ClassPatrimonial = "Património Nacional",
                            Estilo = "Barroco",
                            Tipo = "Edifício"
                        });
                });

            modelBuilder.Entity("MonumentosOnline.Models.Imagens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataImagem")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstadoImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legenda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonumentoFK")
                        .HasColumnType("int");

                    b.Property<string>("NomeImagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilizadorFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonumentoFK");

                    b.HasIndex("UtilizadorFK");

                    b.ToTable("Imagens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataImagem = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Convento de Cristo",
                            MonumentoFK = 1,
                            NomeImagem = "ConventoCristo.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 2,
                            DataImagem = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Igreja São João Baptista",
                            MonumentoFK = 1,
                            NomeImagem = "IgrejaSaoJoaoBaptista.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 3,
                            DataImagem = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Mosteiro dos Jerónimos",
                            MonumentoFK = 1,
                            NomeImagem = "MosteiroJeronimos.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 4,
                            DataImagem = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Mosteiro da Batalha",
                            MonumentoFK = 1,
                            NomeImagem = "MosteiroBatalha.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 5,
                            DataImagem = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Castelo de Leiria",
                            MonumentoFK = 1,
                            NomeImagem = "CasteloLeiria.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 6,
                            DataImagem = new DateTime(2021, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Mosteiro de Alcobaça",
                            MonumentoFK = 1,
                            NomeImagem = "MosteiroAlcobaca.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 7,
                            DataImagem = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Castelo de São Jorge",
                            MonumentoFK = 1,
                            NomeImagem = "CasteloSaoJorge.jpg",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 8,
                            DataImagem = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EstadoImagem = "S",
                            Legenda = "Torre dos Clérigos",
                            MonumentoFK = 1,
                            NomeImagem = "TorreClerigos.jpg",
                            UtilizadorFK = 1
                        });
                });

            modelBuilder.Entity("MonumentosOnline.Models.Monumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtitetoConstrutor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodSIPA")
                        .HasColumnType("int");

                    b.Property<string>("CoordLatitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoordLongitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EpocaConstrucao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UtilizadorFK")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorFK");

                    b.ToTable("Monumentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtitetoConstrutor = "Construtor do Convento de Cristo",
                            CodSIPA = 4718,
                            CoordLatitude = "39 36 15 N",
                            CoordLongitude = "08 25 22 O",
                            Descricao = "Descrição do Convento de Cristo",
                            Designacao = "Convento de Cristo",
                            Endereco = "Igreja do Castelo Templário, 2300-000 Tomar",
                            EpocaConstrucao = "Séc. 12 / 15 / 16 / 17",
                            Localidade = "Tomar",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 2,
                            ArtitetoConstrutor = "Construtor da Igreja São João Baptista",
                            CodSIPA = 6538,
                            CoordLatitude = "39 36 01 N",
                            CoordLongitude = "08 24 51 O",
                            Descricao = "Descrição da Igreja São João Baptista",
                            Designacao = "Igreja de São João Baptista",
                            Endereco = "Rua São João 135, Tomar",
                            EpocaConstrucao = "Séc. 14 / 15 (conjectural) / 16 / 17 / 18",
                            Localidade = "Tomar",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 3,
                            ArtitetoConstrutor = "Construtor do Mosteiro dos Jerónimos",
                            CodSIPA = 6543,
                            CoordLatitude = "38 41 52 N",
                            CoordLongitude = "09 12 24 O",
                            Descricao = "Descrição do Mosteiro dos Jerónimos",
                            Designacao = "Mosteiro dos Jerónimos",
                            Endereco = "Praça do Império 1400-206 Lisboa",
                            EpocaConstrucao = "Séc. 16 / 17 / 18 / 19 / 20",
                            Localidade = "Lisboa",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 4,
                            ArtitetoConstrutor = "Construtor do Mosteiro da Batalha",
                            CodSIPA = 4061,
                            CoordLatitude = "39 39 32 N",
                            CoordLongitude = "08 49 33 O",
                            Descricao = "Descrição do Mosteiro da Batalha",
                            Designacao = "Mosteiro da Batalha",
                            Endereco = "Largo Infante Dom Henrique, 2440-109 Batalha",
                            EpocaConstrucao = "Séc. 14 / 15 / 16 / 19 / 20",
                            Localidade = "Batalha",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 5,
                            ArtitetoConstrutor = "Construtor do Castelo de Leiria",
                            CodSIPA = 3312,
                            CoordLatitude = "39 44 49 N",
                            CoordLongitude = "08 48 34 O",
                            Descricao = "Descrição do Castelo de Leiria",
                            Designacao = "Castelo de Leiria",
                            Endereco = "Largo de São Pedro, 2400-235 Leiria",
                            EpocaConstrucao = "Séc. 12 / 16 / 20",
                            Localidade = "Leiria",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 6,
                            ArtitetoConstrutor = "Construtor do Mosteiro de Alcobaça",
                            CodSIPA = 4719,
                            CoordLatitude = "39 32 54 N",
                            CoordLongitude = "08 58 48 O",
                            Descricao = "Descrição Mosteiro de Alcobaça",
                            Designacao = "Mosteiro de Alcobaça",
                            Endereco = "Praça 25 de Abril 2460-018 Alcobaça",
                            EpocaConstrucao = "Séc. 12 / 14 / 16 / 18 / 19 / 20",
                            Localidade = "Alcobaça",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 7,
                            ArtitetoConstrutor = "Construtor do Castelo de São Jorge",
                            CodSIPA = 3128,
                            CoordLatitude = "38 42 51 N",
                            CoordLongitude = "09 08 00 O",
                            Descricao = "Descrição do Castelo de São Jorge",
                            Designacao = "Castelo de São Jorge",
                            Endereco = "Rua de Santa Cruz do Castelo, 1100-129 Lisboa",
                            EpocaConstrucao = "Séc. 01 (conjectural)",
                            Localidade = "Lisboa",
                            UtilizadorFK = 1
                        },
                        new
                        {
                            Id = 8,
                            ArtitetoConstrutor = "Construtor da Torre dos Clérigos",
                            CodSIPA = 5522,
                            CoordLatitude = "41 08 45 N",
                            CoordLongitude = "08 36 51 O",
                            Descricao = "Descrição da Torre dos Clérigos",
                            Designacao = "Torre dos Clérigos",
                            Endereco = "Rua de São Filipe de Nery, 4050-546 Porto",
                            EpocaConstrucao = "Séc. 18",
                            Localidade = "Porto",
                            UtilizadorFK = 1
                        });
                });

            modelBuilder.Entity("MonumentosOnline.Models.Utilizadores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalidadeUtilizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@monumentosonline.pt",
                            LocalidadeUtilizador = "Data Center",
                            Login = "admin",
                            Nome = "Administrador do Sistema",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "novato@ipt.pt",
                            LocalidadeUtilizador = "Tomar",
                            Login = "novato",
                            Nome = "Utilizador Novato",
                            Password = "abcdef"
                        });
                });

            modelBuilder.Entity("MonumentosOnline.Models.CaractMonumentos", b =>
                {
                    b.HasOne("MonumentosOnline.Models.Caracteristicas", "Caracteristica")
                        .WithMany("ListaMonumentos")
                        .HasForeignKey("CaracteristicaFK");

                    b.HasOne("MonumentosOnline.Models.Monumentos", "Monumento")
                        .WithMany("ListaCaracteristicas")
                        .HasForeignKey("MonumentoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Monumento");
                });

            modelBuilder.Entity("MonumentosOnline.Models.Imagens", b =>
                {
                    b.HasOne("MonumentosOnline.Models.Monumentos", "Monumento")
                        .WithMany("ListaImagens")
                        .HasForeignKey("MonumentoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MonumentosOnline.Models.Utilizadores", "Utilizador")
                        .WithMany("ListaImagens")
                        .HasForeignKey("UtilizadorFK");

                    b.Navigation("Monumento");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("MonumentosOnline.Models.Monumentos", b =>
                {
                    b.HasOne("MonumentosOnline.Models.Utilizadores", "Utilizador")
                        .WithMany("ListaMonumentos")
                        .HasForeignKey("UtilizadorFK");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("MonumentosOnline.Models.Caracteristicas", b =>
                {
                    b.Navigation("ListaMonumentos");
                });

            modelBuilder.Entity("MonumentosOnline.Models.Monumentos", b =>
                {
                    b.Navigation("ListaCaracteristicas");

                    b.Navigation("ListaImagens");
                });

            modelBuilder.Entity("MonumentosOnline.Models.Utilizadores", b =>
                {
                    b.Navigation("ListaImagens");

                    b.Navigation("ListaMonumentos");
                });
#pragma warning restore 612, 618
        }
    }
}
